import type { SettingsEntry } from "../types";

/** Settings catalog entries — extensions section. */
export const EXTENSIONS_ENTRIES: readonly SettingsEntry[] = [
  // ── extensions ──
  {
    id: "ext.plugins",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins",
    labelKey: "ext.plugins.title",
    descKeys: [
      "ext.lead",
      "ext.plugins.installLabel",
      "ext.plugins.recommendedTitle",
      "ext.plugins.installableTitle",
    ],
    keywords: ["plugin", "plugins", "extensions", "chatcut", "codex"],
  },
  {
    id: "ext.plugins.recommended",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins-recommended",
    labelKey: "ext.plugins.recommendedTitle",
    descKeys: ["ext.plugins.recommended.chatcutDesc"],
    keywords: ["chatcut", "codex", "recommended", "推荐", "推薦"],
  },
  {
    id: "ext.skills",
    section: "extensions",
    tab: "skills",
    anchorId: "settings-anchor-ext-skills",
    labelKey: "ext.skills.title",
    descKeys: ["ext.skills.edit", "ext.skills.editDisabledNote"],
    keywords: [
      "skill",
      "skills",
      "slash",
      "SKILL.md",
      "edit skill",
      "技能",
      "编辑技能",
    ],
  },
  {
    id: "ext.skills.discoverExternal",
    section: "extensions",
    tab: "skills",
    anchorId: "settings-anchor-ext-skills-discover",
    labelKey: "ext.skills.discoverExternal",
    descKeys: [
      "ext.skills.discoverExternalDesc",
      "ext.skills.discoverExternalHonesty.configOff",
    ],
    keywords: [
      "claude",
      "cursor",
      "compat",
      "discover",
      "external skills",
      "探测",
      "探測",
    ],
  },
  {
    id: "ext.mcp",
    section: "extensions",
    tab: "mcp",
    anchorId: "settings-anchor-ext-mcp",
    labelKey: "ext.mcp.title",
    descKeys: [
      "ext.mcp.doctor",
      "ext.mcp.add",
      "mcpModal.oauth.authorize",
      "ext.mcp.auth.howToRefresh",
    ],
    keywords: [
      "mcp",
      "model context protocol",
      "server",
      "oauth",
      "authorize",
      "auth",
      "token",
      "credentials",
      "mcp doctor",
      "授权",
      "認證",
      "oauth 授权",
    ],
  },
  {
    id: "ext.agents",
    section: "extensions",
    tab: "agents",
    anchorId: "settings-anchor-ext-agents",
    labelKey: "ext.agents.title",
    descKeys: ["ext.agents.desc", "ext.agents.new"],
    keywords: [
      "agents",
      "agent definition",
      "persona",
      "scaffold",
      "new agent",
      "代理",
      "新建代理",
    ],
  },
  {
    id: "ext.softwareTeamDlc",
    section: "extensions",
    tab: "agents",
    anchorId: "settings-anchor-software-team-dlc",
    labelKey: "softwareTeamDlc.title",
    descKeys: [
      "softwareTeamDlc.uiName",
      "softwareTeamDlc.enable",
      "softwareTeamDlc.enableDesc",
      "softwareTeamDlc.rosterTitle",
      "softwareTeamDlc.sdlcTitle",
      "softwareTeamDlc.install.action",
      "softwareTeamDlc.install.repair",
      "softwareTeamDlc.openInComposer",
      "softwareTeamDlc.shipLocked",
      "softwareTeamDlc.markReviewNote",
      "softwareTeamDlc.markQaNote",
      "softwareTeamDlc.startDelivery",
      "softwareTeamDlc.addTeammateGroup",
      "softwareTeamDlc.pipelineFileOk",
      "softwareTeamDlc.deliveryFilter",
      "softwareTeamDlc.deliveryDetail",
      "softwareTeamDlc.activityLog",
    ],
    keywords: [
      "software works",
      "sdlc studio",
      "software team",
      "ai software dlc",
      "dlc",
      "sdlc",
      "pipeline",
      "handoff",
      "team roster",
      "product",
      "architect",
      "reviewer",
      "qa",
      "workspace pack",
      "install pack",
      "role pack",
      "open in composer",
      "repair pack",
      "install status",
      "ship gate",
      "review notes",
      "qa notes",
      "start a delivery",
      "docs/sdlc",
      "handoff cta",
      "attach-chat",
      "team session",
      "software-works.json",
      "project pipeline",
      "delivery detail",
      "activity log",
      "软件团队",
      "软件团队 dlc",
      "软件工坊",
      "安装角色包",
      "修复缺失",
      "发布门槛",
      "评审备注",
    ],
  },
  {
    id: "ext.hooks",
    section: "extensions",
    tab: "hooks",
    anchorId: "settings-anchor-ext-hooks",
    labelKey: "ext.hooks.title",
    keywords: ["hooks", "hook"],
  },
  {
    /** Legacy id kept for search; lands on plugins installable catalog (no market tab). */
    id: "ext.market",
    section: "extensions",
    tab: "plugins",
    anchorId: "settings-anchor-ext-plugins-catalog",
    labelKey: "ext.plugins.installableTitle",
    descKeys: ["ext.market.title", "ext.plugins.installableLead"],
    keywords: [
      "marketplace",
      "market",
      "install plugin",
      "市场",
      "市場",
      "市集",
      "openai",
      "openai/plugins",
      "catalog",
    ],
  },
];
